# Site Variables
name:             "Terriscope"
description:      "Terriscope - Professional MapServer Support and Development"
url:              "http://www.terriscope.fr"
blog:             "/blog"
blog_categories:  "/blog/categories"
blog_tags:        "/blog/tags"
blog_rss:         "/blog/feed.xml"

# Dependencies
markdown:         rdiscount
pygments:         true

# Blog Permalinks
permalink:        "/blog/:categories/:title/"

# Blog Pagination
paginate:         5
paginate_path:    "/blog/page:num"

# Server Info
exclude:          [".gitignore", "less", "CNAME", "LICENSE", "README.md"]
